### PR TITLE
add CDNJS version badge in README.md

### PR DESCRIPTION
**Pull request by pvnr0082t**
This badge will show the version on CDNJS!

### CODE REVIEW

**Comment by Flyer53** [comment]
Hey there ... and thanks for the extra service :)

One question: Is there anything to do on my side once I release a new version? Or will this be an automated process on CDNJS?

**Comment by pvnr0082t** [comment]
Hi @Flyer53 ,
We set the npm auto-update config for jsPanel3, so just remember to publish the latest version on NPM. The auto-updater in cdnjs will automatically update for the lib once the new version released.:facepunch:

**Comment by Flyer53** [comment]
Thanks a lot 👍

**Comment by Flyer53** [comment]
Hi again,
first of all thanks again for making jsPanel3 available via CDNJS :)
Would you mind considering to also add the previous jsPanel repo https://github.com/Flyer53/jsPanel with the jsPanel versions prior 3.x to CDNJS? The v2.x is still in use (supports more browsers than v3.x) and since it's the original jsPanel repo I'd like to move the 3.x versions to this repo as well (of course the jsPanel3 repo will remain in place). Further I'm working on the next major release 4 which would also go into the original jsPanel repo instead of creating a new jsPanel4 repo.
I think this would be a good thing for erveryone involved. Of course I would provide all necessary files if something is missing like minified files e.g.
Regards, Stefan

**Comment by pvnr0082t** [comment]
Hi @Flyer53 , 
Actually, I have requested `jsPanel` in cdnjs(https://github.com/cdnjs/cdnjs/issues/9131) but still don't have time to send pull request for jsPanel. I will find the time to do it or assign the issue to other contributors in cdnjs to take over this. Thanks for your reminding. :+1:

**Comment by Flyer53** [comment]
Sounds like a plan ... great :)
Thanks a lot 👍

**Comment by pvnr0082t** [comment]
If you want, you can also send pull request to cdnjs. It will be great, too.  We're willing to help you.:tada:

**Pull request merged**
